### ISSUE TITLE
Testing of vertical monitor layout.

### ISSUE THREAD

**Issue by patricknelson** [patricknelson/win10-sticky-mouse#1]
Need help from anyone with a vertical monitor layout to ensure it operates consistently.

**Comment by MathieuLafrance** [comment]
Hi,

I can help, I have the following setup. It works only on the top of <span>#</span>2 and <span>#</span>3. It does not work on the rest:

![image](https://user-images.githubusercontent.com/37808908/37917740-37fcec9a-30ed-11e8-9381-5d756b5169de.png)

I really wasn't able to find any other solution that even seemed to work a little bit. Your solutoin is my only hope. The app from jawfin cannot work inside any corporation as it is flagged as being malware and will never be accepted.

Thanks for any help or code advice you can provide.

**Comment by patricknelson** [comment]
I don't use this app anymore and plan on archiving this repository soon.

@MathieuLafrance would you mind giving MouseUnsnag a try instead and see if that works? The project is now located at https://github.com/MouseUnSnag/MouseUnSnag and the latest release can be [downloaded from here](https://github.com/MouseUnSnag/MouseUnSnag/releases).
