### ISSUE TITLE
Unexpected movement inside fullscreen applications

### ISSUE THREAD

**Issue by diegomolina** [patricknelson/win10-sticky-mouse#4]
Hello. Recently I had been having some problems with my camera moving apparently randomly inside games, until recently when I noticed these "random" movements were only happening when moving the camera towards the top right and bottom right areas (I have a 2 monitor setup and I play on the left monitor). Long story short, I disabled the script during gameplay and stopped having this issue. It seems full screen applications which capture the mouse pointer (like first person view games) will have this problem whenever the real mouse pointer reaches one of the sticky corners, and the issue is much more noticeable when you use lower mouse sensitivity inside those applications. This affected my full screen games but not my fake full screen ones (fills the whole screen but it's treated as a window without borders). I am guessing it could be solved by disabling the script if you are inside a full screen application which captures the pointer, but I have no idea how AHK works.

**Comment by patricknelson** [comment]
Just FYI, I don't actually use this anymore and I plan on archiving this soon. 

**But don't fret!** I found that MouseUnsnag works _beautifully_. The project is now located at https://github.com/MouseUnSnag/MouseUnSnag and the latest release can be [downloaded from here](https://github.com/MouseUnSnag/MouseUnSnag/releases).

**Comment by patricknelson** [comment]
Closing since I'll soon be archiving this repository and pointing folks to a far superior solution: [MouseUnsnag](https://github.com/MouseUnSnag/MouseUnSnag/) 😄
