### ISSUE TITLE
Non-typical layout not working

### ISSUE THREAD

**Issue by ghost** [patricknelson/win10-sticky-mouse#5]
Hey, thanks for writing this script!
for my layout, it's only working between two of the three of my monitors, and only along the top edge between them. the bottoms between the first 2 monitors (between action centre of first monitor and windows start button of second (#3) monitor) it still gets stuck. I've got a third (#2)monitor BELOW and to the RIGHT of my second monitor, for viewing markups closer to my face, and the corners intersecting the second monitor aren't working either. below is an image of the layout. Not sure this is something you can fix, but if so that'd be a welcome revision! 

Thanks so much!
![image](https://user-images.githubusercontent.com/28675801/36855433-a78af794-1d30-11e8-81e5-f760d6627e52.png)

**Comment by MathieuLafrance** [comment]
Same issue here. Green = it works. Red = it doesn't work:

![image](https://user-images.githubusercontent.com/37808908/37917740-37fcec9a-30ed-11e8-9381-5d756b5169de.png)

Thanks for any help or code advice you can provide.

**Comment by patricknelson** [comment]
Just FYI, I don't actually use this anymore and I plan on archiving this soon. 

**But don't fret!** I found that MouseUnsnag works _beautifully_. The project is now located at https://github.com/MouseUnSnag/MouseUnSnag and the latest release can be [downloaded from here](https://github.com/MouseUnSnag/MouseUnSnag/releases).

From my testing so far, it _looks_ like it should be able to resolve each of the issues noted above.  Future versions should allow the ability to persist your preferences on the next startup. For now though, you can at least initialize it using command line parameters (e.g. `-w` to disable wrapping around monitors).

**Comment by patricknelson** [comment]
Closing since I'll soon be archiving this repository and pointing folks to a far superior solution: [MouseUnsnag](https://github.com/MouseUnSnag/MouseUnSnag/) 😄
